using NUnit.Framework;
using SPTarkov.Server.Core.Utils;
using SPTarkov.Server.Core.Utils.Cloners;
using SPTarkov.Server.Core.Utils.Collections;

namespace UnitTests.Tests.Utils;

/// <summary>
///     Cross-language parity pins: every constant below was generated by
///     `cargo test -p spt-native --lib print_kat_vectors -- --ignored --nocapture` and is asserted
///     bit-for-bit by the twin KAT tests in rust/spt-native/src/loot/random_util.rs and
///     probability_object_array.rs. If a constant changes on one side, the other side's twin must
///     change in the same commit.
/// </summary>
[TestFixture]
public sealed class RandomSourceParityTests
{
    private const ulong KatSeed = 42;

    private static readonly ulong[] _katRawU64 = [0x15780B2E0C2EC716UL, 0x6104D9866D113A7EUL, 0xAE17533239E499A1UL, 0xECB8AD4703B360A1UL];

    private static readonly ulong[] _katNextDouble48Bits = [0x3FA65C185D8E2C00UL, 0x3FEB30CDA2274FC0UL, 0x3FD4CC8E79266840UL];

    private static readonly ulong[] _katNextDouble53Bits = [0x3FB5780B2E0C2EC0UL, 0x3FD84136619B444EUL, 0x3FE5C2EA66473C93UL];

    private static readonly byte[] _katFill5 = [0x16, 0xC7, 0x2E, 0x0C, 0x2E];

    private static readonly int[] _katGetInt1To10 = [7, 2, 2, 5, 9];

    /// <summary>
    ///     Pinned for the RandomUtil.GetDouble twin added alongside the seeded RandomUtil wiring.
    /// </summary>
    private static readonly ulong[] _katGetDouble0To100Bits = [0x401177F309171260UL, 0x40553E20A6AEB64EUL, 0x40403FCF4EA60172UL];

    private static readonly bool[] _katGetChance100At50 = [true, true, true, false, false];

    private static readonly string[] _katPoolDraw5 = ["a", "a", "a", "c", "c"];

    private static readonly string[] _katPoolDrawAndRemove3 = ["a", "b", "c"];

    [Test]
    public void RawXoshiroSequenceMatchesTheRustTwin()
    {
        var rng = new Xoshiro256StarStar(KatSeed);

        for (var i = 0; i < _katRawU64.Length; i++)
        {
            Assert.That(rng.NextUInt64(), Is.EqualTo(_katRawU64[i]), $"raw u64 #{i}");
        }
    }

    [Test]
    public void DoubleDerivationsMatchTheRustTwin()
    {
        var source = new SeededRandomSource(KatSeed);
        for (var i = 0; i < _katNextDouble48Bits.Length; i++)
        {
            var bits = BitConverter.DoubleToUInt64Bits(source.NextDouble48());
            Assert.That(bits, Is.EqualTo(_katNextDouble48Bits[i]), $"NextDouble48 #{i}");
        }

        source = new SeededRandomSource(KatSeed);
        for (var i = 0; i < _katNextDouble53Bits.Length; i++)
        {
            var bits = BitConverter.DoubleToUInt64Bits(source.NextDouble53());
            Assert.That(bits, Is.EqualTo(_katNextDouble53Bits[i]), $"NextDouble53 #{i}");
        }
    }

    [Test]
    public void FillMatchesTheRustTwin()
    {
        var source = new SeededRandomSource(KatSeed);
        var buffer = new byte[5];
        source.Fill(buffer);

        Assert.That(buffer, Is.EqualTo(_katFill5));
    }

    [Test]
    public void GetInt32MatchesTheRustGetIntScript()
    {
        // rust `get_int(1, 10)` (inclusive) resolves to `get_int32(1, 11)`.
        var source = new SeededRandomSource(KatSeed);
        for (var i = 0; i < _katGetInt1To10.Length; i++)
        {
            Assert.That(source.GetInt32(1, 11), Is.EqualTo(_katGetInt1To10[i]), $"GetInt32 #{i}");
        }
    }

    [Test]
    public void GetInt32RejectsAnEmptyRangeAsRandomNumberGeneratorDoes()
    {
        var source = new SeededRandomSource(KatSeed);

        Assert.Throws<ArgumentOutOfRangeException>(() => source.GetInt32(5, 5));
        Assert.Throws<ArgumentOutOfRangeException>(() => source.GetInt32(5, 4));
    }

    [Test]
    public void SeededRandomUtilMatchesTheRustDrawScript()
    {
        var randomUtil = DI.GetInstance().GetService<RandomUtil>();
        var original = randomUtil.RandomSource;
        try
        {
            randomUtil.RandomSource = new SeededRandomSource(KatSeed);
            for (var i = 0; i < _katGetInt1To10.Length; i++)
            {
                Assert.That(randomUtil.GetInt(1, 10), Is.EqualTo(_katGetInt1To10[i]), $"GetInt #{i}");
            }

            randomUtil.RandomSource = new SeededRandomSource(KatSeed);
            for (var i = 0; i < _katGetDouble0To100Bits.Length; i++)
            {
                var bits = BitConverter.DoubleToUInt64Bits(randomUtil.GetDouble(0, 100));
                Assert.That(bits, Is.EqualTo(_katGetDouble0To100Bits[i]), $"GetDouble #{i}");
            }

            randomUtil.RandomSource = new SeededRandomSource(KatSeed);
            for (var i = 0; i < _katGetChance100At50.Length; i++)
            {
                Assert.That(randomUtil.GetChance100(50), Is.EqualTo(_katGetChance100At50[i]), $"GetChance100 #{i}");
            }
        }
        finally
        {
            randomUtil.RandomSource = original;
        }
    }

    [Test]
    public void SeededProbabilityObjectArrayMatchesTheRustPoolDraws()
    {
        var cloner = DI.GetInstance().GetService<ICloner>();
        var pool = new ProbabilityObjectArray<string, string>(cloner) { new("a", 5, null), new("b", 1, null), new("c", 1, null) };

        var original = ProbabilityRandomSource.Current;
        try
        {
            ProbabilityRandomSource.Current = new SeededRandomSource(KatSeed);
            Assert.That(pool.Draw(5), Is.EqualTo(_katPoolDraw5));

            ProbabilityRandomSource.Current = new SeededRandomSource(KatSeed);
            Assert.That(pool.DrawAndRemove(3), Is.EqualTo(_katPoolDrawAndRemove3));
        }
        finally
        {
            ProbabilityRandomSource.Current = original;
        }
    }
}
